// ── Legal Compliance Wrapper ──────────────────────────────────────────────────
// Wraps all AI responses with FSC-required disclaimers.
// Keeps Oros in "educational tool" category — no $10M insurance needed.

let prisma;
try { prisma = require('../config/database').prisma; } catch (_) { prisma = null; }
const USE_DB = !!(process.env.DATABASE_URL && prisma);

const LEGAL_DISCLAIMERS = {
  stockAnalysis: {
    short: "⚠️ Educational analysis only. Not investment advice.",
    full: "IMPORTANT DISCLAIMER: This analysis is based on historical data and mathematical models. It is NOT personalized investment advice for your specific situation. Past performance does not guarantee future results. Markets involve risk of loss. Consult a licensed investment advisor before investing. Oros is a technology and information service. We are not a registered investment advisor or broker-dealer."
  },
  portfolioOptimizer: {
    short: "⚠️ Theoretical model. Not a recommendation for YOUR portfolio.",
    full: "PORTFOLIO OPTIMIZATION DISCLAIMER: This is a mathematical simulation based on Modern Portfolio Theory. It shows theoretical allocations, NOT recommendations for you. Based on historical data which may not repeat. Does not account for your tax situation, goals, or risk tolerance. Consult a licensed financial advisor before making any changes."
  },
  aiDeepDive: {
    short: "⚠️ Research tool output. Educational purposes only.",
    full: "AI ANALYSIS DISCLAIMER: This report contains mathematical and statistical analysis of historical market data. It is educational research. Not personalized advice for your situation. AI models have limitations and can be wrong. Always consult a licensed investment advisor before acting on any information in this report."
  },
  aiChat: {
    short: "⚠️ AI responses are educational, not advice.",
    full: "AI ASSISTANT DISCLAIMER: AI responses provide general information and education. They are NOT personalized investment recommendations. AI can make mistakes or provide incomplete information. Your financial situation is unique. Use AI responses for learning, not as the basis for investment decisions."
  },
  financialPlan: {
    short: "⚠️ Illustrative plan only. Not personalized financial advice.",
    full: "FINANCIAL PLAN DISCLAIMER: This is an illustrative plan generated by an AI model using the inputs you provided. It is NOT personalized financial advice. Your actual financial situation, tax obligations, and risk tolerance may differ significantly. Consult a licensed financial advisor before making any investment decisions."
  }
};

const LEGAL_FOOTER = "Oros Ltd. is a financial technology information service. Not a registered investment advisor or broker-dealer.";

function wrapAIResponse(content, featureType, includeFullDisclaimer = false) {
  const disclaimer = LEGAL_DISCLAIMERS[featureType] || LEGAL_DISCLAIMERS.aiChat;
  return {
    content,
    disclaimer: includeFullDisclaimer ? disclaimer.full : disclaimer.short,
    complianceVersion: '1.0',
    timestamp: new Date().toISOString(),
    featureType,
    legalFooter: LEGAL_FOOTER,
  };
}

async function logAIInteraction(userId, featureType, disclaimerShown) {
  if (!USE_DB || !userId) return;
  try {
    await prisma.aiInteractionLog.create({
      data: {
        userId,
        featureType,
        disclaimerShown,
        disclaimerVersion: '1.0',
      },
    });
  } catch (_) {
    // Non-blocking — don't fail the request if logging fails
  }
}

module.exports = { LEGAL_DISCLAIMERS, wrapAIResponse, logAIInteraction, LEGAL_FOOTER };
